// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template_da_pdf_a_HTML.Data;

#nullable disable

namespace Template_da_pdf_a_HTML.Migrations
{
    [DbContext(typeof(RequestContext))]
    [Migration("20250404073804_init8")]
    partial class init8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Autore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataMorte")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("DocumentoUtente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataInserimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataModifica")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Scadenza")
                        .HasColumnType("TEXT");

                    b.Property<int>("idTipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idUtente")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("idTipo");

                    b.HasIndex("idUtente")
                        .IsUnique();

                    b.ToTable("DocumentiUtenti");
                });

            modelBuilder.Entity("Genere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Generi");
                });

            modelBuilder.Entity("Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("AnnoUscita")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataInserimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataModifica")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .HasColumnType("TEXT");

                    b.Property<int>("idAutore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idGenere")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("idAutore");

                    b.HasIndex("idGenere");

                    b.ToTable("Libri");
                });

            modelBuilder.Entity("Prestito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataInizioPrestito")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataInserimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataModifica")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataScadenzaPrestito")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtenteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.HasIndex("UtenteId");

                    b.ToTable("Prestiti");
                });

            modelBuilder.Entity("Richiesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cancellato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Data_inserimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Messaggio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Oggetto")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Richiesta", (string)null);
                });

            modelBuilder.Entity("Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tipi");
                });

            modelBuilder.Entity("Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataInserimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataModifica")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Eliminato")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("DocumentoUtente", b =>
                {
                    b.HasOne("Tipo", "Tipo")
                        .WithMany("DocumentiUtenti")
                        .HasForeignKey("idTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utente", "Utente")
                        .WithOne("DocumentoUtente")
                        .HasForeignKey("DocumentoUtente", "idUtente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Libro", b =>
                {
                    b.HasOne("Autore", "Autore")
                        .WithMany("Libri")
                        .HasForeignKey("idAutore")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Genere", "Genere")
                        .WithMany("Libri")
                        .HasForeignKey("idGenere")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autore");

                    b.Navigation("Genere");
                });

            modelBuilder.Entity("Prestito", b =>
                {
                    b.HasOne("Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Utente", "Utente")
                        .WithMany("Prestiti")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Autore", b =>
                {
                    b.Navigation("Libri");
                });

            modelBuilder.Entity("Genere", b =>
                {
                    b.Navigation("Libri");
                });

            modelBuilder.Entity("Tipo", b =>
                {
                    b.Navigation("DocumentiUtenti");
                });

            modelBuilder.Entity("Utente", b =>
                {
                    b.Navigation("DocumentoUtente");

                    b.Navigation("Prestiti");
                });
#pragma warning restore 612, 618
        }
    }
}
