# Usa l'immagine ufficiale di Nginx
FROM nginx:latest

# Copia i file HTML nella cartella di Nginx
COPY Index.html /usr/share/nginx/html/index.html

# Esponi la porta 80 per il server web
EXPOSE 80

# Avvia Nginx
# -g "daemon off;" serve a far partire Nginx in primo piano
CMD ["nginx", "-g","daemon off;"]

